name: launch_at_startup
description: This plugin allows Flutter desktop apps to Auto launch on startup / login.
version: 0.1.7
homepage: https://github.com/leanflutter/launch_at_startup

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  win32_registry: 1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
